import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// Importar iconos específicos que necesites
import { 
  faShoppingCart, 
  faUser, 
  faCog, 
  faBox, 
  faTools, 
  faSignOutAlt, 
  faSpinner, 
  faChevronDown,
  faBars,
  faHome,
  faStore,
  faHeart,
  faSearch,
  faBell,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faCreditCard,
  faTruck,
  faStar,
  faStarHalfAlt,
  faTrash,
  faEdit,
  faPlus,
  faMinus,
  faCheck,
  faTimes,
  faEye,
  faEyeSlash,
  faLock,
  faUnlock,
  faKey,
  faShieldAlt,
  faInfoCircle,
  faExclamationTriangle,
  faCheckCircle,
  faTimesCircle,
  faChevronLeft,
  faChevronRight,
  faArrowLeft,
  faArrowRight,
  faCamera,
  faCrown,
  faSave,
  faRedo,
  faPalette,
  faDollarSign,
  faUsers,
  faClock,
  faUndo,
  faChartLine,
  faChartBar,
  faClipboardList,
  faExclamationCircle,
  faUserPlus,
  faGlobe,
  faCalendarAlt,
  faLightbulb,
  faUniversity,
  faBolt,
  faSyncAlt,
  faComments,
  faMobileAlt,
  faTag,
  faArrowUp,
  faArrowDown,
  faSort,
  faSortUp,
  faSortDown,
  faTicketAlt,
  faAngleDoubleLeft,
  faAngleDoubleRight
} from '@fortawesome/free-solid-svg-icons'

import { 
  faHeart as faHeartRegular,
  faStar as faStarRegular,
  faUser as faUserRegular,
  faEnvelope as faEnvelopeRegular,
  faBell as faBellRegular
} from '@fortawesome/free-regular-svg-icons'

import { 
  faFacebook,
  faTwitter,
  faInstagram,
  faGoogle,
  faGithub,
  faLinkedin
} from '@fortawesome/free-brands-svg-icons'

// Agregar iconos a la librería
library.add(
  // Solid icons
  faShoppingCart, 
  faUser, 
  faCog, 
  faBox, 
  faTools, 
  faSignOutAlt, 
  faSpinner, 
  faChevronDown,
  faBars,
  faHome,
  faStore,
  faHeart,
  faSearch,
  faBell,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faCreditCard,
  faTruck,
  faStar,
  faStarHalfAlt,
  faTrash,
  faEdit,
  faPlus,
  faMinus,
  faCheck,
  faTimes,
  faEye,
  faEyeSlash,
  faLock,
  faUnlock,
  faKey,
  faShieldAlt,
  faInfoCircle,
  faExclamationTriangle,
  faCheckCircle,
  faTimesCircle,
  faChevronLeft,
  faChevronRight,
  faArrowLeft,
  faArrowRight,
  faCamera,
  faCrown,
  faSave,
  faRedo,
  faPalette,
  faDollarSign,
  faUsers,
  faClock,
  faUndo,
  faChartLine,
  faChartBar,
  faClipboardList,
  faExclamationCircle,
  faUserPlus,
  faGlobe,
  faCalendarAlt,
  faLightbulb,
  faUniversity,
  faBolt,
  faSyncAlt,
  faComments,
  faMobileAlt,
  faTag,
  faArrowUp,
  faArrowDown,
  faSort,
  faSortUp,
  faSortDown,
  faTicketAlt,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  
  // Regular icons
  faHeartRegular,
  faStarRegular,
  faUserRegular,
  faEnvelopeRegular,
  faBellRegular,
  
  // Brand icons
  faFacebook,
  faTwitter,
  faInstagram,
  faGoogle,
  faGithub,
  faLinkedin
)

// Exportar el componente para uso global
export { FontAwesomeIcon }
